FROM node:22-alpine AS builder
WORKDIR /app
COPY src/ /app/src/
COPY prisma/ /app/prisma/
COPY package.json package-lock.json tsconfig.json /app/
RUN npm ci && npm run build


FROM node:22-alpine
WORKDIR /app

ENV HOST="0.0.0.0"
ENV PORT="3000"
ENV RECONNECT_INTERVAL="5000"
ENV MAX_RECONNECT_RETRIES="5"
ENV LOG_LEVEL="warn"
ENV NODE_ENV="production"

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/prisma /app/prisma
COPY --from=builder /app/package.json /app/package-lock.json /app/

EXPOSE 3000/tcp
CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npm run start"]
