version: "3.8"

services:
    baileys-db:
        image: postgres:17-alpine
        container_name: baileys-db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:?missing_DB_PASSWORD}
            POSTGRES_DB: baileys
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    baileys-api:
        container_name: baileys-api
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgres://postgres:${DB_PASSWORD}@baileys-db:5432/baileys
            API_KEY: ${BAILEYS_API_KEY:?missing_BAILEYS_API_KEY}
        depends_on:
            baileys-db:
                condition: service_healthy
        restart: unless-stopped

volumes:
    postgres:
